runtime: python
env: flex
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1
https://yungceo-ahejhwc4avhrgtb2.canadacentral-01.azurewebsites.net/

